[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/Dockerfile.ui"

[deploy]
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
